#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --account=XXX
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1

#SBATCH --job-name=XXX
#SBATCH --mem=40000
#SBATCH --time=0-48:00:00
#SBATCH --output=XXX
#SBATCH --partition=XXX

BPE_REMOVER=tools/bpe_remover.py
TRANSLATE=../translate.py
TEST_SRC=path/to/test_src
TEST_TGT=path/to/test_tgt
DEV_SRC=path/to/dev_src
DEV_TGT=path/to/dev_tgt
BLEU=tools/multi-bleu.perl
TEST_TGT_RAW=path/to/raw_test_tgt
DEV_TGT_RAW=path/to/raw_dev_tgt

. /usr/local/anaconda/5.1.0-Python3.6-gcc5/etc/profile.d/conda.sh
conda activate XXX

BASEDIR=$(dirname "$0")

echo "Testing model(s) ..."
for model in $BASEDIR/checkpoints/model_T0_*.pt
do
         echo ${model}
        python3 $TRANSLATE -gpu 0 -model $model -report_bleu -output ${model}.preds.bpe -src $TEST_SRC -tgt $TEST_TGT > ${model}.stats 2>&1
        python3 $TRANSLATE -gpu 0 -model $model -report_bleu -output ${model}.dpreds.bpe -src $DEV_SRC -tgt $DEV_TGT > ${model}.dstats 2>&1

         python $BPE_REMOVER ${model}.preds.bpe ${model}.preds
         python $BPE_REMOVER ${model}.dpreds.bpe ${model}.dpreds

         perl $BLEU $TEST_TGT_RAW < ${model}.preds > ${model}.tbleu
         perl $BLEU $DEV_TGT_RAW < ${model}.dpreds > ${model}.dbleu
done

echo "Testing is finished!"
